### ISSUE TITLE
建议更新管家婆的match匹配范围

### ISSUE THREAD

**Issue by jagger235711** [tampermonkeyStorage/Self-use#14]
## 问题描述
今天在学习js时候打开控制台发现了管家婆向控制台输出的log。

它出现在了错误的网站，而不是仅出现在几个匹配的网盘域名范围内。

## 问题定位
@match匹配不严谨建议修改。否则可能导致异常的浏览器性能开销

**Comment by tampermonkeyStorage** [comment]
脚本有一个很重要的功能是记住所有浏览过的网站出现的网盘链接和提取码，这便于自动填写，所以应该在所有网址保存运行
当然你可以排除当前网址，脚本管理器很容易做到
